name: checksum
description: An application to check multiple checksums at once.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ^2.1.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0